Make brigtness-conrol work with any eDP device

diff --git a/local/bin/brightness-control b/local/bin/brightness-control
--- a/local/bin/brightness-control
+++ b/local/bin/brightness-control
@@ -1,30 +1,34 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-CURBR="$(xrandr --current --verbose|grep 'Brightness:'|head -1|awk '{print $2}')"
+CURBR=$(xrandr --current --verbose|grep 'Brightness:'|head -1|awk '{print $2}')
+DEV=$(xrandr --current --verbose|grep 'eDP' | awk '{print $1}')
 STEP="0.05"
 MAXBR="1.0"
 MINBR="0"
-echo "current brightness" $CURBR
+
+[[ -z "$CURBR" ]] && echo "Error: could not get current brightness" && exit 1
+
+echo "Current device: $DEV brightness: $CURBR"
 
 case "$1" in
     U|u|[U,u]p)
         # increase brightness by 5%
-        _brightness=$(echo $CURBR+$STEP|bc)
-        echo "desired new brightness" $_brightness
-        _res=$(echo "$_brightness <= $MAXBR"|bc)
-        if [ "$_res" -eq 1 ]; then
-            echo "new brightness" $_brightness
-            xrandr --output eDP-1 --brightness $_brightness
+        _brightness=$(echo "$CURBR+$STEP" | bc)
+        echo "Desired new brightness: $_brightness"
+        _res=$(echo "$_brightness > $MAXBR" | bc)
+        if [[ "$_res" -eq 0 ]]; then
+            echo "New brightness: $_brightness"
+            xrandr --output "$DEV" --brightness $_brightness
         fi
         ;;
     D|d|[D,d]own|[D,d]o)
         # increase brightness by 5%
-        _brightness=$(echo $CURBR-$STEP|bc)
-        echo "desired new brightness" $_brightness
-        _res=$(echo "$_brightness >= $MINBR"|bc)
-        if [ "$_res" -eq 1 ]; then
-            echo "new brightness" $_brightness
-            xrandr --output eDP-1 --brightness $_brightness
+        _brightness=$(echo "$CURBR-$STEP" | bc)
+        echo "Desired new brightness: $_brightness"
+        _res=$(echo "$_brightness < $MINBR" | bc)
+        if [[ "$_res" -eq 0 ]]; then
+            echo "New brightness: $_brightness"
+            xrandr --output "$DEV" --brightness $_brightness
         fi
         ;;
     *)
